### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by alisonjo315** [terminus-plugin-project/terminus-code-plugin#2]
Hi!  Thoughts/feelings about creating a PHP 8 compatible version of this plugin?

Locally, I very roughly tried installing it with a clone of the repo and manually changing the PHP requirement in composer.json to add `|| ^8.0`  🙃   (I didn't even change the terminus "compatible-version", even though I'm using terminus 3.1.0)

It seems to work just fine! 🤞🤞🤞

Is there more that would need to happen to release a PHP 8 compatible version of this plugin? -- and/or is there a preference not to release a new version of this plugin?  I'll create a PR just with the change I described, in case it's useful as a starting place.

Thank you!

----

P.S. I know there's the `local:clone` command built into terminus now, but you can't change the directory path with that command, it always puts the code in `$HOME/pantheon-local-copies` (the most you can do is specify a sub-directory inside there, not a totally different location).

**Comment by uberhacker** [comment]
There shouldn't be an issue running this with php 8 as long as the terminus version you are using can work with php 8. 
 Not sure why this didn't close with the PR.
